steps:
  - command: echo "I am agent $NAME"
  - command: docker run -d -t --name ${BUILDKITE_PIPELINE_SLUG}-agent -e  BUILDKITE_AGENT_DISCONNECT_AFTER_JOB=true -e  BUILDKITE_AGENT_NAME=${BUILDKITE_PIPELINE_SLUG}-agent -e  BUILDKITE_AGENT_TAGS="queue=${BUILDKITE_PIPELINE_SLUG}"  buildkite/agent:3 start --token $BK_TOKEN